export interface AddInterface{
	id?:string;	
	address?:string;
	altitud?:string;
	cantD?:number;
	cantidad?:number;
	capacidad?:number;
	category?:string;
	categoryFilter?:string;
	check?:Array<boolean>;
	codigo?:string;
	color?:string;
	con?:Array<number>;
	description?:string;
	desLg?:string;
	dificulty?:string;
	discount?:number;
	disponibilidad?:string;
	distancia?:string;
	duracion?:string;
	finalPrice?:number;
	globalPrice?:number;
	images?:Array<string>;
	modelo?:string;
	new?:boolean;
	notes?:string;
	precio?:number;
	price?:number;
	productName?:string;
	sin?:Array<number>;
	status?:string;
	tallas?:Array<string>;
	temp?:string;
	tips?:string;
	typePrice?:string;
	userd?:string;
	
}