export interface CardInterface{
	id?:string;
	type?:string;
	userd?:string;
	name?:string;
	phone?:string;
	companyName?:string;
	address?:string;
	url?:string;
	companyAddress?:string;
	username?:string;
	surname?:string;
	country?:string;
	route?:string;
	city?:string;
	status?:string;
	images?:Array<string>;
	services?:Array<any>;
}